config/routes.rb
Rails.application.routes.draw do
  devise_for :users, only: [:omniauth_callbacks], :controllers => { :omniauth_callbacks => "corumiauth" }

  root 'home#index'
  get 'test1', to: "home#test1" 
  
  delete 'logout', to: "home#logout" 
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/corumiauth_controller.rb
class CorumiauthController < ApplicationController

  def facebook
    # session[:user] = request.env['omniauth.auth']
    param = request.env['omniauth.auth']
    user = User.new(
      fb_username: param['info']['name'],
      email: param['info']['email'],
    )
    if user.save
      sign_in(user)
      flash[:success] = "berhasil login"
      redirect_to root_path
    else
      #  do something
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
  end

  def test1
  end

  def logout
    # session[:user] = nil
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/corumiauth/facebook.html.erb
<%= request.env['omniauth.auth'].to_json %>

app/views/home/index.html.erb
<% if session[:user].present? -%>
  Halo <%= session[:user]['info']["name"] -%>,
  <%= link_to "Logout",  logout_path, method: :delete %>
<% else -%>
  <%= link_to "Login facebook", user_omniauth_authorize_path(:facebook) %>
<% end -%> 

app/views/home/test1.html.erb
<%= session[:data] -%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Corumi</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>